[Feature] can now disable auto deploy message taken from last commit

diff --git a/bin/git-up b/bin/git-up
--- a/bin/git-up
+++ b/bin/git-up
@@ -58,6 +58,7 @@ hotfix=1
 release=0
 revertto=
 resync=0
+deploymsg=
 GITROOT=
 
 #
@@ -69,23 +70,23 @@ Usage() {
 }
 
 error() {
-    echo "\033[41m\033[1;33mCRITICAL: $@\033[0m"
+	echo "\033[41m\033[1;33mCRITICAL: $@\033[0m"
 	exit 42
 }
 warn () {
-    echo "\033[41m\033[1;33mWARNING: $@\033[0m"
+	echo "\033[41m\033[1;33mWARNING: $@\033[0m"
 }
 
 info () {
-    echo "\033[44m\033[1;36m$@\033[0m"
+	echo "\033[44m\033[1;36m$@\033[0m"
 }
 
 msg () {
-    echo "\033[40m\033[1;36m$@\033[0m"
+	echo "\033[40m\033[1;36m$@\033[0m"
 }
 
 msgy () {
-    echo "\033[40m\033[1;33m$@\033[0m"
+	echo "\033[40m\033[1;33m$@\033[0m"
 }
 
 debug() {
@@ -359,20 +360,20 @@ check_pushed() {
 }
 
 resync() {
-    set +e
-	ssh $sshopts $sshhost up $upopts "$repolongname" $stage sync "$commitish"
-    # sometimes ssh exists with return code 1 without any errors, even when
-    # "up ... sync" command exits with 0.
-    # ugly hack, but in case of an error with "up" command, it doesn't return 1 
-    # but a bigger number.
-    local retsshcode=$?
-    set -e
-    if [ $retsshcode -eq 1 ]
-    then
-        return 0
-    else
-        return $retsshcode
-    fi
+	set +e
+	echo "$deploymsg" | ssh $sshopts $sshhost up $upopts "$repolongname" $stage sync "$commitish"
+	# sometimes ssh exists with return code 1 without any errors, even when
+	# "up ... sync" command exits with 0.
+	# ugly hack, but in case of an error with "up" command, it doesn't return 1 
+	# but a bigger number.
+	local retsshcode=$?
+	set -e
+	if [ $retsshcode -eq 1 ]
+	then
+		return 0
+	else
+		return $retsshcode
+	fi
 }
 
 
@@ -600,6 +601,31 @@ else
 			exit 7
 		fi
 	else
+		if [ -n "$allow_auto_deploy_message" ] && [ $allow_auto_deploy_message -eq 0 ] && [ "$stage" = "$tag_stage" ] 
+		then
+			blockcolor="\033[44m\033[1;37m"
+			echo -n $blockcolor
+			echo ">--------------------------------------------------------------------<"
+			#echo "\033[0m"
+			echo -n -e "$deploy_message_prompt"
+			echo "\033[0m"
+
+			deploymsgvalid=0
+			while [ $deploymsgvalid -eq 0 ]
+			do
+				echo -n "Message: "
+				deploymsg=
+				while read line
+				do
+					[ -z "$line" ] && break
+					deploymsg="$deploymsg$line\n"
+				done
+				if [ -n "$deploymsg" ]
+				then
+					deploymsgvalid=1
+				fi
+			done
+		fi
 		resync
 	fi
 	exit 0
