feat/minimum-deploymsg-size

diff --git a/adc/up b/adc/up
--- a/adc/up
+++ b/adc/up
@@ -48,7 +48,7 @@ msg () {
 	echo "\033[40m\033[1;36m$@\033[0m" >&2
 }
 
-msgy () { 
+msgy () {
 	echo "\033[40m\033[1;33m$@\033[0m" >&2
 }
 
@@ -87,14 +87,14 @@ get_conf() {
 			warn "You should add your organization and projects specific config files in $orgconfdir."
 		else
 			debug "Update internal git-up config repository ($PWD/$orgconfdir)"
-			# can't use --work-tree parameter as we are in a git repository ... 
+			# can't use --work-tree parameter as we are in a git repository ...
 			# so I use a subshell
 			( unset GIT_DIR; cd $orgconfdir && git pull $( test $debug -eq 0 && echo -q ) --ff-only origin master )  >&2
 		fi
 
 		for confdir in $defaultconfdir $orgconfdir
 		do
-			for conffile in defaults.cfg organization.cfg ${repo}.default.cfg ${repo}.cfg 
+			for conffile in defaults.cfg organization.cfg ${repo}.default.cfg ${repo}.cfg
 			do
 				local cnf=$confdir/$conffile
 				if [ -e $cnf ]
@@ -467,7 +467,7 @@ parse_ansible_hostfile() {
 	#debug "Call ansible: $lansible"
 	#local hosts=$( $lansible --inventory "$hostfile" --list-hosts $repo | awk '{print $1}' )
 	local hosts=$( awk '/\['$repo'\]/ { f=1; next; } /\[/ {f=0; next;} /./ && f {print $1}' < "$hostfile" )
-	
+
 	debug "Hosts found: $hosts"
 	# master is first if not already setup
 	for h in "$hosts"
@@ -627,7 +627,7 @@ do_sync() {
         exit 42
     fi
 
-	# Not at Christmas {{{ 
+	# Not at Christmas {{{
     if [ "$( date +%d-%m )" = "24-12" ] && [ "$stage" = "prod" ]
     then
         echo "\033[40m\033[1;31m" >&2
@@ -709,7 +709,7 @@ EOF
         _____j     '-.....-'     |    )(    |          |,--.
    ____/ /  /\\\\ ,-._.--------.-.-' ,-')('-. |          |\\';/
 .-()___  :  |'.!,-'''/'-._  (___) (  '  '  )'-._    _.-'|;,|
-'-,    \\_\\__\\',-'>-.,-._           '-....-'     ''''    '--'  
+'-,    \\_\\__\\',-'>-.,-._           '-....-'     ''''    '--'
   '-._       ('- '-._'-.'
 
 EOF
@@ -727,15 +727,15 @@ EOF
 		cat <<EOF >&2
 ┐┌┐┌┐
 ┘└┘└┘ ╲😨ފ
-┐┌┐┌┐ ／ 
+┐┌┐┌┐ ／
 ┘└┘└┘ノ)
-┐┌┐┌┐ 
+┐┌┐┌┐
 ┘└┘└┘
 ┐┌┐┌┐ Sorry, it's friday 🤷
 ┘└┘└┘
-┐┌┐┌┐ 
+┐┌┐┌┐
 │││││
-┴┴┴┴┴ 
+┴┴┴┴┴
 EOF
 		echo "\033[0m" >&2
 		exit 42
@@ -775,7 +775,7 @@ EOF
 	if [ -n "$inventory" ]
 	then
 		debug "inventory=$inventory"
-		# Replace REPOSITORY and STAGE parameters 
+		# Replace REPOSITORY and STAGE parameters
 		#for i in $( seq 1 ${#inventory[@]} )
 		#do
 		#	inventory[$i]="$( echo "${inventory[$i]}" | sed "s/REPOSITORY/$repo/; s/STAGE/$stage/;" )"
@@ -817,7 +817,7 @@ EOF
 		#find $gitdir -type f -print0 | xargs -0 chmod ug+r
 		find $gitdir -type d -print0 | xargs -0 chmod u=rwx,g=rwxs
 	fi
-	
+
 
 	local after=$( git rev-parse HEAD )
 
@@ -829,13 +829,18 @@ EOF
 		git whatchanged --stat --format="%n%Cred author : %an --- %Cgreen date :  %ad%n %h - %s %Creset" $after..$before
 		echo
 	fi
-	
+
 	local deploymsg=
 	if [ -n "$GITUPVERSION" ] && [ $GITUPVERSION -gt 1 ]
 	then
 		deploymsg="$(</dev/stdin)"
 	fi
 	debug "Deploymsg: ##$deploymsg##"
+
+	if [[ ${#deploymsg} -lt $minimum_deploy_message_size ]]; then
+		echo "Deploy message error\n$deploymsg\nMessage is too short (minimum 20 characters)"
+		exit 32
+	fi
 
 	hook "pre_deploy" $before $after $( get_user )
 	local_hook "pre-deploy" $before $after $( get_user ) $sync_to
@@ -866,33 +871,33 @@ EOF
 
 	if [ $debug -gt 0 ]
 	then
-		sync_cmd="$sync_cmd 
+		sync_cmd="$sync_cmd
 --debug"
 	fi
 
 	if [ $quick -gt 0 ]
 	then
-		sync_cmd="$sync_cmd 
+		sync_cmd="$sync_cmd
 --quick"
 	fi
 
 	debug "mutualized=$mutualized"
 	if [ $mutualized -gt 0 ]
 	then
-		sync_cmd="$sync_cmd 
+		sync_cmd="$sync_cmd
 --mutu"
 	fi
 
 	if [ -n "$servers" ]
 	then
-		sync_cmd="$sync_cmd 
+		sync_cmd="$sync_cmd
 --servers=$servers"
 	fi
 
 	local tags=$( echo -n "$deploymsg" | grep -Eo '#(\w+)' | tr "\n" "," )
 	if [ -n "$tags" ]
 	then
-		sync_cmd="$sync_cmd 
+		sync_cmd="$sync_cmd
 --tags=$tags"
 	fi
 
@@ -930,7 +935,7 @@ EOF
 	return 0
 }
 
-# 
+#
 # MAIN
 #
 #if [ -n "$SSH_ORIGINAL_COMMAND" ]
@@ -1015,6 +1020,6 @@ do
 	shift
 done
 
-# TODO: 
+# TODO:
 # - check that sync_to is in the future
 #   else, use --force
