First step done: - clone if necessary - else fetch - compare versions : current stage vs. what we want

diff --git a/adc/up b/adc/up
--- a/adc/up
+++ b/adc/up
@@ -2,27 +2,328 @@
 
 
 set -e
-
+shopt -s xpg_echo
 cd $( dirname $0 )
 
+postreceivehook="../../.gitolite/hooks/common/post-receive"
+repositories=
+provisiondir=
+repo=
+stage=
+commitish=
+confdir=../conf.d
+debug=0
+sync_to=
+
+
+# GIT INFOS
+chead=
+ctag=
+cpretty=
+gitdir=
+gitopts=
+NOREV="0000000000000000000000000000000000000000"
+
+
+error () {
+    echo "\033[41m\033[1;33mCRITICAL: $@\033[0m" >&2
+}
+
+warn () {
+	echo "\033[41m\033[1;33mWARNING: $@\033[0m" >&2
+}
+
+info () {
+	echo "\033[44m\033[1;36m$@\033[0m" >&2
+}
+
+msg () {
+	echo "\033[40m\033[1;36m$@\033[0m" >&2
+}
+
+msgy () { 
+    echo "\033[40m\033[1;33m$@\033[0m" >&2
+}
+
+debug() {
+	if [ $debug -gt 0 ]
+	then
+		echo "# DEBUG: [$( date -R )] <<< $@" >&2
+	fi
+}
+
+is_gitolite() {
+	if [ -n "$GL_USER" ]
+	then
+		return 0
+	fi
+	return 1
+}
+
+is_gitlab() {
+	getent passwd | grep -q gitlab
+	return $?
+}
+
+# From http://theoldschooldevops.com/2008/02/09/bash-ini-parser/
+cfg_parser ()
+{
+	ini="$(<$1)"
+	ini="${ini//[/\[}"          # escape [
+	ini="${ini//]/\]}"          # escape ]
+	IFS=$'\n' && ini=( ${ini} ) # convert to line-array
+	ini=( ${ini[*]//;*/} )      # remove comments with ;
+	ini=( ${ini[*]//#*/} )      # remove comments with #
+	ini=( ${ini[*]/\    =/=} )  # remove tabs before =
+	ini=( ${ini[*]/=\   /=} )   # remove tabs be =
+	ini=( ${ini[*]/\ =\ /=} )   # remove anything with a space around =
+	ini=( ${ini[*]/#\\[/\}$'\n'cfg.section.} ) # set section prefix
+	ini=( ${ini[*]/%\\]/ \(} )    # convert text2function (1)
+	ini=( ${ini[*]/=/=\( } )    # convert item to array
+	ini=( ${ini[*]/%/ \)} )     # close array parenthesis
+	ini=( ${ini[*]/%\\ \)/ \\} ) # the multiline trick
+	ini=( ${ini[*]/%\( \)/\(\) \{} ) # convert text2function (2)
+	ini=( ${ini[*]/%\} \)/\}} ) # remove extra parenthesis
+	ini[0]="" # remove first element
+	ini[${#ini[*]} + 1]='}'    # add the last brace
+	#debug "$(echo "${ini[*]}")"
+	eval "$(echo "${ini[*]}")" # eval the result
+}
+
+get_conf() {
+	# do not reparse every time
+	if ! type cfg.section.general >/dev/null 2>&1 
+	then
+		# Example: fetch or update config files
+		hook pre_conf
+		for conffile in default.ini organization.ini ${repo}.default.ini ${repo}.ini 
+		do
+			cnf=$confdir/$conffile
+			if [ -e $cnf ]
+			then
+				debug "Parse $cnf"
+				cfg_parser $cnf
+			fi
+		done
+		hook post_conf
+	fi
+}
+
+hook() {
+	if [ -n "$1" ]
+	then
+		local hookname="$1"
+		local hook=
+		# Can't get conf on pre_conf hook
+		if [ "$hookname" = "pre_conf" ]
+		then
+			hook="../hooks/pre_conf"
+		# any other hooks:
+		else
+			get_conf
+			cfg.section.hooks
+			hook="${!1}"
+		fi
+		debug "hook '$hookname' ?"
+		if [ -n "$hook" ]
+		then
+			if [ -x "$hook" ]
+			then
+				debug "Call hook: $hook"
+			else
+				debug "hook $1 => '$hook' : script not found."
+			fi
+		fi
+	fi
+}
+
+do_update() {
+	get_conf
+	cfg.section.general
+	debug "do auto-update: $do_auto_update_each"
+	if [ -n "$do_auto_update_each" ] && [ $do_auto_update_each -gt 0 ]
+	then
+		# TODO: flag + check last update
+		cd ..
+		debug "self-update"
+		hook pre_self_update
+		git pull
+		if is_gitolite
+		then
+			if diff -q hooks/post-receive $postreceivehook
+			then
+				echo "Updating gitolite post-receive hook."
+			#	cp -a hooks/post-receive $postreceivehook
+			fi
+		elif is_gitlab
+		then
+			warn "GITLAB is not yet supported."
+		fi
+		debug "self-update done."
+		hook post_self_update
+	else
+		error "auto-update is disabled"
+	fi
+	exit 0
+}
+
+setup_provision() {
+	if is_gitolite
+	then
+		repositories="$GL_REPO_BASE_ABS"
+		provisiondir="$GL_REPO_BASE_ABS/../provisioning/$stage"
+	elif is_gitlab
+	then
+		error "GITLAB is not yet supported."
+	else
+		provisiondir="../../provisioning/$stage"
+	fi
+	if [ ! -d "$provisiondir" ]
+	then
+		debug "mkdir $PWD/$provisiondir"
+		mkdir -p "$provisiondir"
+	fi
+
+	local cloned=0
+	if [ ! -d "$provisiondir/$repo" ]
+	then
+		msgy "Clone $repo, please wait ..."
+		if ! git clone -l -q $repositories/${repo}.git $provisiondir/$repo >&2
+		then
+			echo "# FATAL: unable to clone $repo."
+			exit 7
+		fi
+		cloned=1
+	fi
+	gitdir="$provisiondir/$repo"
+	export GIT_WORK_TREE="$gitdir"
+	export GIT_DIR="$gitdir/.git"
+	debug "git fetch"
+	git fetch --tags -q origin
+	debug "git fetch done."
+
+	# init on commitish
+	if [ $cloned -gt 0 ]
+	then
+		msg "Initialize to $commitish"
+		git checkout -q $commitish
+	fi
+
+	chead="$( git rev-parse HEAD )"
+	set +e
+	cabbrev="$( git rev-parse --abbrev-ref HEAD )"
+	debug "cabbrev=$cabbrev"
+	if [ "$cabbrev" != "HEAD" ]
+	then
+		cbranch="$cabbrev"
+		cpretty="$cbranch"
+	else
+		cpretty=$chead
+	fi
+	ctag="$( git describe --tags --exact-match $chead 2>/dev/null )"
+	if [ -n "$ctag" ]
+	then
+		cpretty="$ctag"
+	fi
+	debug "cpretty=$cpretty chead=$chead ctag='$ctag'"
+	set -e
+}
+
+do_infos() {
+	check_repo
+	setup_provision
+	get_conf
+
+	cfg.section.on_receive
+	if [ -n "$tag_stage" ] && [ "$tag_stage" = "$stage" ]
+	then
+		debug "Stage <$stage> is configured on tags."
+		echo "tag=1"
+		echo "tag_pattern='$tag_pattern'"
+	else
+		echo "tag=0"
+	fi
+
+	echo "chead='$chead'"
+	echo "ctag='$ctag'"
+	echo "cpretty='$cpretty'"
+}
+
+check_repo() {
+	if [ -z "$repo" ]
+	then
+		error "repository not found."
+		exit 6
+	fi
+	if [ -z "$stage" ]
+	then
+		error "stage not found."
+		exit 7
+	fi
+
+	get_conf
+	cfg.section.general
+	
+	for allowed_stage in ${allowed_stages[*]}
+	do
+		if [ "$stage" = "$allowed_stage" ]
+		then
+			return 0
+		fi
+	done
+	error "Stage <$stage> is not allowed."
+	exit 8
+}
+
+do_sync() {
+	info "Delivering $repo to $stage on $sync_to ..."
+	echo "WIP: step 2, deploy !" >&2
+}
+
+# 
+# MAIN
+#
 while [ $# -gt 0 ]
 do
 	case "$1" in
 		test)
 			exit 0
-			shift
 			;;
 		autotag)
 			shift
 			exec ../bin/autotag.pl --nofetch --short $@
 			;;
 		update)
-			cd ..
-			exec git pull
+			do_update
+			;;
+		infos)
+			do_infos
+			;;
+		sync)
+			shift
+			sync_to="$1"
+			do_sync
+			;;
+		--debug)
+			debug=1
+			debug "Call $0 $@"
+			;;
+		--init)
+			shift
+			commitish="$1"
 			;;
 		*)
-			echo "You are not supposed to do that, go away !"
-			exit 42
+			if [ -z "$repo" ]
+			then
+				repo="$1"
+			elif [ -z "$stage" ]
+			then
+				stage="$1"
+			else
+				echo "You are not supposed to do that, go away !"
+				exit 42
+			fi
 			;;
 	esac
+	shift
 done
diff --git a/bin/git-up b/bin/git-up
--- a/bin/git-up
+++ b/bin/git-up
@@ -1,14 +1,25 @@
 #!/bin/bash
-# Usage: git up [--force] [--check] <env> [commit-ish]
+# Usage: git up [options] <stage> [commit-ish]
 # Deploy commit to production servers
+# --help        : this help
 # --force		: ...
 # --check		: check before and display diff
 # --info		: get current working tree infos
-# 
+# --debug       : for bug fixing (please use it for issues)
+#
+#With options:
+#    <stage> hotfix          : quick hotfix
+#    <stage> release         : new release
+#    <stage> revert TOREF    : revert <stage> to TOREF
+#    <stage> diff            : diff between stage and your HEAD
+#    <stage> whatchanged     : whatchanged between <stage> and your HEAD
+#    <stage> sync            : re-sync prod or preprod
+#
+#TIPS:
+#    <stage> hotfix -p       : params -* are passed to git log
+#
 # https://github.com/ezweb/git-up
 
-
-[ "$1" = "--help" ] && { sed -n -e '/^# Usage:/,/^$/ s/^# \?//p' < $0; exit; }
 
 set -e
 shopt -s xpg_echo
@@ -20,28 +31,59 @@ shopt -s xpg_echo
 # Search git-up on those remotes :
 remotes="prod production origin"
 sshopts="-x -A"
+remoteuri=
 remote=
 sshhost=
+reponame=
 LANG=C
+stage=
+debug=0 # --debug
+check=0
+force=0
+diff=0
+upopts=
+commitish=
+newtag=
 
 # deprecated?
 hotfix=1
 release=0
 revertto=
-diff=0
-sshhost=
-reponame=
-ezgit="ez_git"
-prod=
-ppbranch=
 resync=
 
 # 
 # FUNCTIONS
 #
-error () {
+
+Usage() {
+	{ sed -n -e '/^# Usage:/,/^$/ s/^# \?//p' < $0; exit; }
+}
+
+error() {
     echo "\033[41m\033[1;33mCRITICAL: $@\033[0m"
 	exit 42
+}
+warn () {
+    echo "\033[41m\033[1;33mWARNING: $@\033[0m"
+}
+
+info () {
+    echo "\033[44m\033[1;36m$@\033[0m"
+}
+
+msg () {
+    echo "\033[40m\033[1;36m$@\033[0m"
+}
+
+msgy () {
+    echo "\033[40m\033[1;33m$@\033[0m"
+}
+
+debug() {
+	if [ $debug -gt 0 ]
+	then
+		echo "% DEBUG: [$( date -R )] >>> $@" >&2
+	fi
 }
 
 check_prerequisites() {
@@ -49,45 +91,34 @@ check_prerequisites() {
 	do
 		if ! type $tool >/dev/null
 		then
-			echo "FATAL: the tool '$tool' is required."
-			exit 2
+			error "the tool '$tool' is required."
 		fi
 	done
 }
+
 
 get_remote() {
 	for search in $remotes
 	do
 		if git remote show -n | grep -q "^$search$"
 		then
-			remote=$( git remote show -n "$search" | grep "Fetch URL" | awk '{print $3}' )
-			sshhost=${remote%%:*}
+			remote="$search"
+			remoteuri=$( git remote show -n "$search" | grep "Fetch URL" | awk '{print $3}' )
+			sshhost=${remoteuri%%:*}
+			reponame=${remoteuri##*:}
+			reponame=${reponame##*/}
+			reponame=${reponame%%.git}
 			return
 		fi
 	done
 	error "Remote not found."
 }
 
+
 check_connection() {
-	echo "Trying to connect to $sshhost ..."
+	echo -n "Trying to connect to $sshhost ... "
 	ssh $sshopts $sshhost up test
-}
-
-# ------------------------------
-
-config_ssh() {
-	local sshuser=$( git config --get ez.sshuser )
-	if [ -z "$sshuser" ]
-	then
-		echo "FATAL: not configured."
-		exit 4
-
-	elif [ "$sshuser" = "SYSTEM" ]
-	then
-		sshhost=$lab
-	else
-		sshhost="$sshuser@$lab"
-	fi
+	echo OK.
 }
 
 
@@ -102,84 +133,89 @@ get_next_tag() {
 	then
 		autotag="perl $( dirname $0 )/autotag.pl"
 	else
-		echo "hint: install Perl for better performance ;)" >&2
+		msgy "hint: install Perl for better performance ;)" >&2
 		autotag="ssh $sshopts $sshhost up autotag"
 	fi
+	debug "autotag: $autotag"
+	tag_pattern=
+	debug "hotfix=$hotfix release=$release pattern=$tag_pattern"
+
+	# with tag pattern, grep all
+	if [ -z "$tag_pattern" ]
+	then
+		tag_pattern=".*"
+	fi
+
 	if [ $hotfix -gt 0 ]
 	then
-		newtag=$( git tag -l | $autotag --nofetch --short )
+		newtag=$( git tag -l | grep -E "$tag_pattern" | $autotag --nofetch --short )
 	elif [ $release -gt 0 ]
 	then
-		newtag=$( git tag -l | $autotag --nofetch --short --release )
+		newtag=$( git tag -l | grep -E "$tag_pattern" | $autotag --nofetch --short --release )
 	fi
 }
-
-
-repo_name() {
-	if [ -z "$reponame" ]
-	then
-		reponame=$( git remote show -n origin | grep Fetch | cut -d":" -f3 )
-	fi
-	echo $reponame
-}
-
 
 fetch_info() {
 	if [ -z "$ppbranch" ]
 	then
-		config_ssh
-		infofile="$HOME/.ez.info.$$"
-		> $infofile
-		ssh -C $sshhost $ezgit --remote --project "$( repo_name )" info >$infofile
-		# TODO: gérer un pb de connexion ssh
-		. $infofile
-		rm -f $infofile
-	fi
-}
-
-
-check_branch() {
-	fetch_info
-	curbranch=$( git branch | grep '^*' | cut -d" " -f2 )
-	if [ -n "$curbranch" ] && [ -n "$ppbranch" ]
-	then
-		if [ "$curbranch" = "$ppbranch" ]
+		msg "[$stage] Fetch current ref ..."
+		infofile="/tmp/${USER}.git-up-info.$$"
+		if ssh $sshopts $sshhost up $upopts "$reponame" $stage --init "$commitish" infos >$infofile
 		then
-			return 0
+			. $infofile
+			if [ $debug -gt 0 ]
+			then
+				debug "----------------------------"
+				cat $infofile >&2
+				debug "----------------------------"
+			fi
+			rm -f $infofile
+		else
+			cat $infofile
+			rm -f $infofile
+			exit 8
 		fi
+		if [ -z "$chead" ]
+		then
+			error "Failed to get current ref for <$stage>"
+		fi
+		info "======[ $reponame<$stage> is on $remote/$cpretty ]======"
 	fi
-	echo "ERROR: you are not in '$ppbranch'."
-	exit 6
 }
 
 
-resync() {
-	ssh -C $sshhost $ezgit --remote --project "$( repo_name )" sync $1
-}
-
-
-check_param_prod() {
-	if [ "$1" = "prod" ] || [ "$1" = "preprod" ]
+check_pushed() {
+	ref=$( git rev-parse $commitish )
+	if git cherry | grep -q "$ref$"
 	then
-		return 0
+		commits=$( git cherry | wc -l )
+		m="You have to push your commits ! ($commits commit"
+		if [ $commits -gt 1 ]
+		then
+			m="${m}s"
+		fi
+		m="$m waits to be pushed)"
+		error "$m"
 	fi
-	return 1
 }
 
-diff() {
+# ------------------------------
+#resync() {
+#	ssh -C $sshhost $ezgit --remote --project "$( repo_name )" sync $1
+#}
+#
+#
+gitdiff() {
 	diff=$1
 	shift
-	d1="HEAD"
-	if [ "$diffwith" = "preprod" ]
+	d1=HEAD
+	if [ -n "$1" ]
 	then
-		d2="origin/$ppbranch"
-	else
-		d1="origin/$ppbranch"
-		d2="$prod"
+		d1="$1"
+		shift
 	fi
-	echo "DIFF: $@ $d2..$d1"
-	echo "(debug: prod_commit_id=$phead with=$diffwith prodtag=$prod)"
-	echo "(debug: preprod_commit_id=$pphead)"
+	d2="$cpretty"
+	msg "[$stage] DIFF: $@ $d2..$d1"
 	if [ $diff -eq 1 ]
 	then
 		git diff $@ $d2 $d1
@@ -194,72 +230,73 @@ diff() {
 
 
 gitopts=""
-# Traitement des options
 while [ $# -gt 0 ]
 do
 	case "$1" in
 		hotfix) # default ...
 			hotfix=1
 			release=0
-			shift
 			;;
 		release)
 			release=1
 			hotfix=0
-			shift
 			;;
 		revert)
 			release=0
 			hotfix=0
 			revertto=$2
 			shift
-			shift
 			;;
 		diff)
 			diff=1
-			shift
-			diffwith=$1
-			shift
 			;;
 		sync)
 			resync=$2
 			shift
-			shift
 			;;
 		whatchanged)
 			diff=2
-			shift
-			diffwith=$1
-			shift
+			;;
+		--check)
+			check=1
+			;;
+		--force)
+			force=1
+			;;
+		--help)
+			Usage
+			;;
+		--debug)
+			debug=1
+			upopts="--debug "
 			;;
 		# git opts
 		-*)
 			gitopts="$gitopts $1"
-			shift
 			;;
 		*)
-			cat <<EOF
-Usage: git up [options]
-
-With options:
-    hotfix                  : quick hotfix
-    release                 : new release
-    revert prod    TOREF    : revert prod to TOREF
-    revert preprod TOREF    : revert preprod to TOREF
-    diff prod               : diff between prod and preprod
-    diff preprod            : diff between preprod and origin/master
-    whatchanged prod        : whatchanged between prod and preprod
-    whatchanged preprod     : whatchanged between preprod and origin/master
-    sync prod|preprod: re-sync prod or preprod
-
-TIPS:
-    hotfix -p               : params -* are passed to git log
-
-EOF
-			exit 1
+			if [ -z "$stage" ]
+			then
+				stage="$1"
+			elif [ -z "$commitish" ]
+			then
+				commitish="$1"
+			else
+				Usage
+			fi
 			;;
 	esac
+	shift
 done
+
+if [ -z "$stage" ]
+then
+	Usage
+fi
+if [ -z "$commitish" ]
+then
+	commitish=HEAD
+fi
 
 check_prerequisites
 
@@ -267,48 +304,32 @@ get_remote
 
 check_connection
 
-echo "wip..."; exit 12
-
 up_to_date
 
 fetch_info
 
+if [ $debug -gt 0 ]
+then
+	msgy "-------------------"
+	echo stage=$stage
+	echo repo=$reponame
+	echo remoteuri=$remoteuri
+	echo remote=$remote
+	echo "-------------------"
+	echo hotfix=$hotfix
+	echo release=$release
+	echo diff=$diff
+	msgy "-------------------"
+fi
+
+
 # DIFF / WHATCHANGED
 if [ $diff -gt 0 ]
 then
-	diff $diff
-
-# MISE EN PROD
-elif [ $hotfix -gt 0 -o $release -gt 0 ]
-then
-	check_branch
-
-	newtag=
-	get_next_tag
-	if [ -z "$newtag" ]
-	then
-		echo "An unexpected error occurred while computing next tag."
-		exit 2
-	fi
-
-	diff 3 $gitopts # whatchanged
-	echo
-	echo "|----------------------------------------------------"
-	echo "| Project: $( repo_name ) origin/$ppbranch $prod"
-	echo "|----------------------------------------------------"
-	echo
-	printf "Please validate this hotfix to {$newtag} [yYnN] : "
-	read proceed
-	if [ "$proceed" = "y" ] || [ "$proceed" = "Y" ] # || [ "$proceed" = "" ]
-	then
-		git tag $newtag && git push origin $newtag
-	else
-		echo "CANCELED."
-		exit 7
-	fi
-	exit 0
+	gitdiff $diff
 elif [ -n "$revertto" ]
 then
+	warn "wip..."; exit 12
 	if check_param_prod	
 	then
 		resync "$1"
@@ -317,15 +338,56 @@ then
 	fi
 elif [ -n "$resync" ]
 then
+	warn "wip..."; exit 12
 	if check_param_prod	
 	then
 		resync "$1"
 	else
 		exec $0 help # Usage
 	fi
+
+# DEPLOY
 else
-	echo "Not yet implemented..."
-	exit 8
+	check_pushed
+	if [ $tag -gt 0 ]
+	then
+		get_next_tag
+		if [ -z "$newtag" ]
+		then
+			echo "An unexpected error occurred while computing next tag."
+			exit 2
+		fi
+	fi
+
+
+	gitdiff 3 $commitish $gitopts # whatchanged
+	if [ $tag -gt 0 ]
+	then
+		blockcolor="\033[44m\033[1;37m"
+		echo -n $blockcolor
+		echo -n "|---------------------------------------------------------------------"
+		echo "\033[0m"
+		echo -n $blockcolor
+		echo -n "|                                                                    |\r"
+		echo -n "| Project: $reponame | Stage: $stage | $cpretty => $newtag "
+		echo "\033[0m"
+		echo -n $blockcolor
+		echo -n "|---------------------------------------------------------------------"
+		echo "\033[0m"
+		printf "Please validate this $( test $release -gt 0 && echo release || echo hotfix ) [yYnN] : "
+		read proceed
+		if [ "$proceed" = "y" ] || [ "$proceed" = "Y" ] # || [ "$proceed" = "" ]
+		then
+			# should trigger deploy :
+			git tag $newtag && git push $remote $newtag
+		else
+			echo "CANCELED."
+			exit 7
+		fi
+	else
+		ssh $sshopts $sshhost up $upopts "$reponame" $stage sync "$commitish"
+	fi
+	exit 0
 fi
 
 
